Doc
openhwgroup/core-v-mcu pull request #104
Opened 2021-04-18 05:59 UTC by timsaxe

This commit sets up the documentation framework:
rtl/../data/file.csv for files that define registers
docs/Makefile copies csv into a mirror directory (there is probably a better make way, but I haven;t taken the time to find it)
docs/Makefile runs util/ioscript.py to convert the csv files into auto-doc/*.md
docs/Makefile runs Sphinx to combine doc-src/*, auto-doc/* into the document tree which can be found in _build/html

csv files and ioscript were modified to put module description before the register descriptions

overview.md was updated to include more information, especially about software validation

2021-04-19 08:22 UTC, zarubaf requested changes
Thanks a lot. This looks very clean!

2021-04-19 08:22 UTC, zarubaf commented on docs/core-v-mcu-user-manual.rst
> +    auto-docs/udma_i2cm_reg_defs
Would you mind adding back a link to the Github page `github.rst`. We can also put it under a specific directory?

2021-04-19 08:22 UTC, zarubaf commented on util/ioscript.py
> +#!/bin/python3
That's great. I think @gmartin102  also added the `ioscript` to another folder. Can we make sure that we only have one version in the repo (e.g., deleting the other one)? I think having it under `util/` makes the most sense.

Maybe a small license header would also be nice :-)

2021-04-19 17:05 UTC, timsaxe commented on docs/core-v-mcu-user-manual.rst
> +    auto-docs/udma_i2cm_reg_defs
I was wondering what to do with github.rst.  Just need to decide where it fits.

2021-04-19 17:06 UTC, timsaxe commented on util/ioscript.py
> +#!/bin/python3
Licenses is more than nice if I recall Eclipse foundation requirements.  Greg and I had discussed and agreed on utils, so I need to find the other and eliminate it.

2021-04-21 04:47 UTC, zarubaf approved these changes

2021-04-21 04:48 UTC, merged