Addr width
openhwgroup/core-v-mcu pull request #109
Opened 2021-04-21 03:32 UTC by gmartin102

Fixed the address width problem and a number of other things that were not in the original pull request.  removed ila mark_debug statements

2021-04-22 12:51 UTC, zarubaf requested changes
I'll also look into the Verible problem :-)

2021-04-22 12:51 UTC, zarubaf commented on core-v-mcu-config.h
> + * WITHOUT WARRANTIES ORETH CONDITIONS OF ANY KIND, either express or implied.
I don't think you meant to change this :-)

2021-04-22 12:51 UTC, zarubaf commented on fpga/core-v-mcu-nexys/openocd-nexys-hs2.cfg
> +#jtag newtap $_CHIPNAME unknown0 -irlen 5 -expected-id 0x10102001
Just delete it, we have version control if we want to get back :-)

2021-04-22 12:51 UTC, zarubaf commented on fpga/core-v-mcu-nexys/openocd-nexys-olimex.cfg
> +#jtag newtap $_CHIPNAME unknown0 -irlen 5 -expected-id 0x10102001
Same here.

2021-04-22 12:51 UTC, zarubaf commented on rtl/core-v-mcu/top/pad_frame.sv
> +module pad_frame(
That module apparently fails CI :(  You said that you ran `format-verible` before pushing?

You can also try running it manually - I'll also quickly check on my end :-)

2021-04-22 12:51 UTC, zarubaf commented on rtl/includes/pulp_peripheral_defines.svh
> + * WITHOUT WARRANTIES ORETH CONDITIONS OF ANY KIND, either express or implied.
I think that's also accidental

2021-04-22 12:51 UTC, zarubaf commented on install-core-v-mcu
> +  && python3 util/ioscript.py\
Awesome, would you mind also deleting the `ioscript` in the top-level with this PR?

2021-04-22 12:54 UTC, zarubaf commented
Strange, running `./util/format-verible` changes the formatting for me. Let me know if it still doesn't work for you - I can take care of it.

2021-04-22 13:21 UTC, gmartin102 commented
@zarubaf I think I fixed everything nd pushed up to QL namespace.

2021-04-22 13:49 UTC, gmartin102 commented
@zarubaf I see we have conflicts in ioscript.  I resolved them in my local branch and pushed the fixes.  you should be able to take the new ioscript in its entirety

2021-04-24 06:50 UTC, zarubaf approved these changes
Perfect, thanks a lot @gmartin102

2021-04-25 07:23 UTC, zarubaf commented
Manually merged on the command line.

2021-04-25 07:23 UTC, closed without merging