Irq fix
openhwgroup/core-v-mcu pull request #119
Opened 2021-04-26 14:46 UTC by gmartin102

This updates fc_subsystem to correct the interrupt inputs to the cv32e40p.  they are connected to the unmasked irq output array from the apb_interrupt_cntrl

2021-04-26 15:50 UTC, gmartin102 commented
I attempted to resolve the conflicts.. mostly formatting issues, except for ioscript.py

2021-04-27 07:11 UTC, zarubaf requested changes

2021-04-27 07:11 UTC, zarubaf commented on util/ioscript.py
> +
There seems to be trailing whitespaces. Can you set your editor to trim those, please?

2021-04-27 07:11 UTC, zarubaf commented on util/ioscript.py
> +
Trailing space.

2021-04-28 19:56 UTC, zarubaf commented
I though I wrote you am answer here but I can’t seem to find it. Just rerun the ˋmake allˋ in the docs folder and commit the docs, then we are good to go!

2021-04-29 05:30 UTC, zarubaf commented
Okay Tests are passing. Just briefly want to check with you that you are okay with the updated doc (you can view them in your repo or see the new doc in the diff) then I’ll merge. To me it looks the IO script broke because of a merge. Let me know!

2021-05-19 17:12 UTC, gmartin102 commented
Closed and opeing a new pull request against master

2021-05-19 17:12 UTC, closed without merging