June14merge
openhwgroup/core-v-mcu pull request #139
Opened 2021-06-14 13:04 UTC by gmartin102

Cumulative merge of changes from Quicklogic

2021-06-14 13:51 UTC, zarubaf requested changes
Generally looks okay from my side except for the LGPL License of the I2C IP that we can't accept here (and would also be problematic in your project). Any idea what to do about this? CC/ @MikeOpenHWGroup @jeremybennett @davideschiavone 

Please also merge the latest OpenHW Group master - so that we do not introduce a lint regression ;-D

2021-06-14 13:51 UTC, zarubaf commented on rtl/apb_i2cs/rtl/FIFO_sync_256x8.v
> +/* ----------------------------------------------------------------------------
We need a file header here :-)

2021-06-14 13:51 UTC, zarubaf commented on rtl/apb_i2cs/rtl/RAM_256x8_behavioral.v
> +/* ----------------------------------------------------------------------------
License header, please

2021-06-14 13:51 UTC, zarubaf commented on rtl/apb_i2cs/rtl/apb_i2cs.v
> +/* ----------------------------------------------------------------------------
License header, please

2021-06-14 13:51 UTC, zarubaf commented on rtl/apb_i2cs/rtl/apb_slv_interface.v
> +
License header, please

2021-06-14 13:51 UTC, zarubaf commented on rtl/apb_i2cs/rtl/i2c_peripheral_interface.v
> +/* ----------------------------------------------------------------------------
License header, please

2021-06-14 13:51 UTC, zarubaf commented on rtl/apb_i2cs/rtl/i2c_peripheral_interface.v
> +//////////////////////////////////////////////////////////////////////
Ah, I think that needs to go on top. But I see problems with the license, we generally can't have LGPL licensed things in here as this would taint the rest of the liberal licenses source code.

2021-06-14 13:59 UTC, gmartin102 commented on rtl/apb_i2cs/rtl/i2c_peripheral_interface.v
> +//////////////////////////////////////////////////////////////////////
Since this is QL source I think we can use the same license header as we use on the other QL source?  If so, I'll fix and resubmit.  --- I thought I was up to date with OpenhwGroup master, but I will also double check that.

2021-06-14 14:04 UTC, MikeOpenHWGroup commented
Its my understanding that OpenHW cannot accept code covered by the LGPL License.  I will confirm.  @DBees, can you comment?

2021-06-15 08:05 UTC, davideschiavone commented
> 
> 
> Its my understanding that OpenHW cannot accept code covered by the LGPL License. I will confirm. @DBees, can you comment?

My understanding is also that we can accept permissive licence only contributions, as for example Solderpad and Apache

2021-06-15 12:42 UTC, MikeOpenHWGroup commented
Update on the LGPL license.  The OpenHW Group cannot accept the LGPL for repositories covered by the [CORE-V Eclipse Foundation project](https://projects.eclipse.org/projects/openhw.corev/developer).  Recall that the Eclipse Foundation process helps us ensure the correct licensing and attribution of our open-source artifacts.  However, core-v-mcu is _not_ covered by the CORE-V Eclipse Foundation project _at this time_.

So, this means:
- We can accept the LGPL licensing for this PR.
- If we do that, the LGPL licensing will need to be resolved before OpenHW can make this a CORE-V project with proper attribution of open source licensing.  This is done through a formal "CQ Process".

Bottom line: it would be far better to resolve this now by removing the LGPL license and adding a permissive licence to this contribution, as for example Solderpad and Apache.  This can only be done by the current copyright holder.

@gmartin102, can you change the copyright on the affected files and update this PR?

2021-06-15 12:54 UTC, gmartin102 commented
@zarubaf - I think I added the Solderpad license header to the new i2c IP, If there is something else in error please let me know what and where and I'll correct it.  I'm a little confused about the LGPL license and where is was referenced

2021-06-15 17:58 UTC, zarubaf commented
The problem is that the I2C core seems to originate from OpenCores and was originally licensed under LGPL, at least that’s what the stray license header indicated. We can not change the license - that must be done by the original author.

2021-07-01 14:34 UTC, gmartin102 reviewed
@zarubaf or @davideschiavone -- Do i need to fix anything on my end? or can you resolve the  conflicts for this PR?

2021-07-01 14:37 UTC, davideschiavone commented
> @zarubaf or @davideschiavone -- Do i need to fix anything on my end? or can you resolve the conflicts for this PR?

I don't have the rights to do it but I can help you if you need -

2021-07-01 14:46 UTC, gmartin102 commented
@davideschiavone  I don't have rights to resolve either, it seems two files are in conflict, the README.md -- which should be an easy resolution and the core-v-mcu.core file -- which the QL build process doesn't use.  we moved that file to the root directory as core-v-mcu-emul.core file to avoid the warnings(?) about referencinf something outside the current directory tree.  -- So bottom line I don't see these as issues for the build

2021-07-01 14:53 UTC, zarubaf commented
@gmartin102 That should do it!
```
git remote add upstream git@github.com:openhwgroup/core-v-mcu.git
git fetch upstream
git merge upstream/master
```

2021-07-01 15:01 UTC, gmartin102 commented
@davideschiavone , @zarubaf , Little bit of research and I think i fixed the conflicts.  but I am seeing a lint checkk fail, not sure how to fix that.  please advise.

2021-07-02 14:27 UTC, davideschiavone commented
the make lint seems to fail... what do you get in your terminal?

2021-07-02 15:00 UTC, gmartin102 commented
Davide, I am seeing the following message,
ERROR: openhwgroup.org<http://openhwgroup.org>:systems:core-v-mcu-orig:0 : Fileset 'verilator-waiver', requested by target 'default', was not found

The issue seems to arise from the fact the Tim has moved? Or copied the core-v-mcu.core file that was in the rtl/core-v-mcu directory to the top level directory and renamed it core-v-mcu-emulation in the top level and changed  some reference in the top level core-v-mcu.core file.
I believe he was seeing a warning about not having files pulled from directories not in the current tree.  Lots of rtl is in parallel directories to the rtl/core-v-mcu.
I see the Florian and Jeremy have been adding options for Verilator lint the rtl/core-v-mcu/core-v-mcu.core file and I suspect those changes need to be properly implemented in the new core-v-emulation.core.
I’ll investigate more and work with Tim to see if I can figure out how to fix this without losing Florian/Jeremys intent.

Greg



On Jul 2, 2021, at 9:27 AM, Pasquale Davide Schiavone ***@***.******@***.***>> wrote:

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



the make lint seems to fail... what do you get in your terminal?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/openhwgroup/core-v-mcu/pull/139#issuecomment-873040184>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AP2QBU2KC5Q2XQF42O5OLADTVXEERANCNFSM46VGHZ6A>.

2021-07-16 00:54 UTC, gmartin102 commented
@davideschiavone -- can you approve this pull request?  I think all issues are resolved.

2021-07-23 14:10 UTC, zarubaf approved these changes
Perfect, thanks @gmartin102!

2021-07-23 14:11 UTC, merged