update README for Verilator
openhwgroup/core-v-mcu pull request #147
Opened 2021-07-03 19:59 UTC by davideschiavone

2021-07-05 10:58 UTC, jeremybennett requested changes
With the clarification I have suggested this will be good to commit.

2021-07-05 10:58 UTC, jeremybennett commented on README.md
> +Install Verilator v4.100: https://verilator.org/guide/latest/install.html
I think you may need to clarify that this is for running the pre-commit checks. The software modeling relies on features in v4.200 or later. So for softrware you need something at least as new as this.

2021-07-05 11:02 UTC, davideschiavone commented on README.md
> +Install Verilator v4.100: https://verilator.org/guide/latest/install.html
Hi @jeremybennett - let's wait for @zarubaf to decide whether we go for 4.1 or 4.2 as the CI is built on the 4.1

2021-07-05 11:05 UTC, jeremybennett commented on README.md
> +Install Verilator v4.100: https://verilator.org/guide/latest/install.html
That's fine. I think using 4.100 is fine for most uses, but for the software you need a special case where you need 4.200.

2021-07-23 14:12 UTC, zarubaf commented on README.md
> +Install Verilator v4.100: https://verilator.org/guide/latest/install.html
So can we update the CI to run on `4.200`, so that we check our claims? Should be quite straight forward changing this line https://github.com/openhwgroup/core-v-mcu/blob/74abb262a9d821a0704fb81784a2739cbc25c714/.github/workflows/ci.yml#L28
`4.200`

2021-09-17 18:40 UTC, merged