Dev
openhwgroup/core-v-mcu pull request #191
Opened 2021-11-05 17:22 UTC by gmartin102

resolves many issue.. some of which were resolved in previous commits, but not closed. Issues addressed include #190, #189, #155, #137, #120, #115, #108, #89, and #69.

2021-11-05 17:28 UTC, jeremybennett commented
@gmartin102 I'll just check this with the Verilator model environment...

2021-11-05 18:16 UTC, jeremybennett commented
@gmartin102 The Verilator model works exactly the same with your changes - including the FPU register and CSR bugs :-( From this perspective I'm happy for this to be merged.

2021-11-05 23:38 UTC, MikeOpenHWGroup requested changes
Looks good @gmartin102, just a few nit-picky items:

1.Delete `a2_boot/A2_boot.elf`.  We should not check-in compile artifacts.
2. A couple of comments about how the cv32e40p_core is instantiated in fc_subsystem.sv
3. 3. There are a number of large files in `tb/mem_init_files`.  Are these necessary or can be there generated on-the-fly?

2021-11-05 23:38 UTC, MikeOpenHWGroup commented on rtl/core-v-mcu/fc/fc_subsystem.sv
> +		  .FPU(0),
Its good to expand the instance parameters, but why not set the `USE_FPU` parameter (see line 13 of this file).  Of course, you'd need to set the default to 0.  Also, `PULP_XPULP` is still 1 and it should be 0.

2021-11-05 23:38 UTC, MikeOpenHWGroup commented on rtl/simulation/a2_bootrom.sv
> +    input  logic                  CEN,
`CEN` is not used.

2021-11-08 13:41 UTC, davideschiavone reviewed
is the BOOT ROM generated with the OpenHW Group compiler without XPULP and FPU instructions?

2021-11-08 13:41 UTC, davideschiavone commented on rtl/includes/pulp_soc_defines.sv
> +`define USE_FPU       1
shouldn't it be 0?

2021-11-08 14:56 UTC, gmartin102 commented on rtl/includes/pulp_soc_defines.sv
> +`define USE_FPU       1
Yes USE_FPU should be 0, but it should also be removed as the instantiation is not using the define, It is hardcoded in the fc_subsystem.  I will correct to either use the define (0) or remove the define if it stays hardcoded.

2021-11-08 14:59 UTC, gmartin102 commented
> is the BOOT ROM generated with the OpenHW Group compiler without XPULP and FPU instructions?

@davideschiavone what compiler flags do I need to add/remove to be compatible with XPULP=0?  the boot code uses no -march options, but my test programs use -march=rv32imac and that seems incompatible with XPULP=0

2021-11-08 15:04 UTC, davideschiavone commented
> > is the BOOT ROM generated with the OpenHW Group compiler without XPULP and FPU instructions?
> 
> @davideschiavone what compiler flags do I need to add/remove to be compatible with XPULP=0? the boot code uses no -march options, but my test programs use -march=rv32imac and that seems incompatible with XPULP=0

@jeremybennett can for sure help more than me, but the FLAGs used should be the one we used to verify the v1 core, and they should be RV32IMC (no A)

2021-11-09 08:19 UTC, jeremybennett commented
> @jeremybennett can for sure help more than me, but the FLAGs used should be the one we used to verify the v1 core, and they should be RV32IMC (no A)

IIRC RM32IMAC is the default for the 32-bit RISC-V compiler. But we should be explicit, and also be explicit about the ABI, so compile using `-march=rv32imc -mabi=ilp32`

2021-11-09 14:28 UTC, gmartin102 commented
@zarubaf @davideschiavone ,
CI checks are failing on my latest PR, looks like a tool installation issue?

2021-11-10 16:50 UTC, MikeOpenHWGroup commented on rtl/includes/pulp_soc_defines.sv
> +`define USE_FPU       1
Agreed.  Let's just remove `define USE_FPU` altogether.

While we are at it, we could also remove `CORE_TYPE` and `USE_HWPE` as these macros are not used in the MCU.  There are parameters of the same name that _are_  used and having parameters and macros with the same name is both confusing and dangerous.

2021-11-12 18:24 UTC, MikeOpenHWGroup approved these changes

2021-11-12 18:24 UTC, merged